steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/ui-service:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '--cache-from', 'gcr.io/$PROJECT_ID/ui-service:latest',
          '-t', 'gcr.io/$PROJECT_ID/ui-service:latest', 
          '-f', 'devops/Dockerfile', 
          '.'
        ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
          'compute',
          '--project', 'smart-car-insurance-hybrid',
          'ssh', 'instance-3',
          '--zone', 'us-central1-a',
          '--command', '
            /home/marco/scih-machine/restart.sh
          '
        ]
images: ['gcr.io/$PROJECT_ID/ui-service:latest']
